// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YourAppNamespace.Data;

#nullable disable

namespace PatientSyncApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YourAppNamespace.Models.DiagnosisRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Suggestion")
                        .HasColumnType("text");

                    b.Property<string>("SymptomCombo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DiagnosisRules");
                });

            modelBuilder.Entity("YourAppNamespace.Models.Patient", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<double>("Bmi")
                        .HasColumnType("double precision");

                    b.Property<bool>("ConsentGiven")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiagnosisNote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("HeightCm")
                        .HasColumnType("double precision");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OtherSymptoms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SyncError")
                        .HasColumnType("text");

                    b.Property<bool>("Synced")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("WeightKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("YourAppNamespace.Models.PatientImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<string>("PatientId")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientImages");
                });

            modelBuilder.Entity("YourAppNamespace.Models.PatientSymptomRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PatientId")
                        .HasColumnType("text");

                    b.Property<int>("SymptomId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("SymptomId");

                    b.ToTable("PatientSymptomsRecord");
                });

            modelBuilder.Entity("YourAppNamespace.Models.Symptom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Symptoms");
                });

            modelBuilder.Entity("YourAppNamespace.Models.SyncQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SyncError")
                        .HasColumnType("text");

                    b.Property<bool>("Synced")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EntityName", "Synced");

                    b.ToTable("SyncQueue");
                });

            modelBuilder.Entity("YourAppNamespace.Models.PatientImage", b =>
                {
                    b.HasOne("YourAppNamespace.Models.Patient", "Patient")
                        .WithMany("Images")
                        .HasForeignKey("PatientId");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("YourAppNamespace.Models.PatientSymptomRecord", b =>
                {
                    b.HasOne("YourAppNamespace.Models.Patient", "Patient")
                        .WithMany("Symptoms")
                        .HasForeignKey("PatientId");

                    b.HasOne("YourAppNamespace.Models.Symptom", "Symptom")
                        .WithMany()
                        .HasForeignKey("SymptomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Symptom");
                });

            modelBuilder.Entity("YourAppNamespace.Models.Patient", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Symptoms");
                });
#pragma warning restore 612, 618
        }
    }
}
